In [15]:
import pandas as pd
import numpy as np
import math
import scipy.stats as st
import warnings
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
warnings.filterwarnings(action='ignore')

In [24]:
# 동일성 검정, 독립성 검정 

In [20]:
# 적합도 검정 
# 주사위
a = [1,2,3,4,5,6,]
b = [18,17,23,21,18,23]

a = np.array(a)
b = np.array(b)

p = 1/6
df = len(a)-1
E =  b.sum() *(p)
print(E)

# 검정 통계 값
T = (((b-E)**2)/E).sum()

print(T)

20.0
1.8


In [21]:
# 검정 통계량 관측
t0 = T
print("P_value",(1-st.chi2.cdf(abs(t0),df)))

P_value 0.87606840032466


In [23]:
# 카이 제곱
# t_a  5% 유의 확률
a =1- 0.05
t_a = st.chi2.ppf(a,df)
print(t_a)


if t_a > T :
    print("H0 기각 x")

11.070497693516351
H0 기각 x


In [43]:
# 독립성 검정     소득 분위 A,B,C  / 찬 반 x y 


#    A.   B.  C 
x = [185,218,198]
y = [156,143,100]


obs = np.array([x,y])
chi2, p, dof, ex =st.chi2_contingency(obs)

print(ex,4)

print("검정 통계:",round(chi2,4)) # 검정 통계

print(round(dof,4))

a =1- 0.05
t_a = st.chi2.ppf(a,dof)
print("기각역:",t_a)

T = round(chi2,4 ) 

if t_a > T :
    print("H0 기각 x")
else:
    print("H0 기각 O")
    

print("유의 확률",round(p,4))  # 유의 확률 보다 작으면  기각
    


[[204.941 216.961 179.098]
 [136.059 144.039 118.902]] 4
검정 통계: 9.8751
2
기각역: 5.991464547107979
H0 기각 O
유의 확률 0.0072


In [44]:
# 동일성성 검정    번주혀어 , 3개 이상 모집단의 비율이 서로 동일 한가?


#    A.   B.  C 
x = [25,25,15]
y = [125,95,115]


obs = np.array([x,y])
chi2, p, dof, ex =st.chi2_contingency(obs)

print(ex,4)

print("검정 통계:",round(chi2,4)) # 검정 통계

print(round(dof,4))

a =1- 0.05
t_a = st.chi2.ppf(a,dof)
print("기각역:",t_a)

T = round(chi2,4 ) 

if t_a > T :
    print("H0 기각 x")
else:
    print("H0 기각 O")
    

print("유의 확률",round(p,4))  # 유의 확률 보다 작으면  기각
    

[[ 24.375  19.5    21.125]
 [125.625 100.5   108.875]] 4
검정 통계: 3.9919
2
기각역: 5.991464547107979
H0 기각 x
유의 확률 0.1359
