In [5]:
import math 
import numpy as np
import pandas as pd 

In [30]:
x = np.array([[1,2],[1,4],[1,6],[1,8],[1,10]])
y = np.array([ [7],[5],[4],[2],[1] ])

In [10]:
print(y)

[[7]
 [5]
 [4]
 [2]
 [1]]


In [40]:
xt=(x.T)

In [41]:
arr_inv=np.linalg.inv(xt@x)

In [42]:
print(arr_inv)

[[ 1.1   -0.15 ]
 [-0.15   0.025]]


In [24]:
p=arr_inv@xt

In [25]:
p@y

array([[ 8.3 ],
       [-0.75]])

In [26]:
y.T@y

array([[95]])

In [35]:
x1=x@arr_inv
print(x1)

[[ 0.8  -0.1 ]
 [ 0.5  -0.05]
 [ 0.2   0.  ]
 [-0.1   0.05]
 [-0.4   0.1 ]]


In [38]:
p1=x1@x.T

In [39]:
y.T@p1@y

array([[94.7]])